language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - rbx-2
  - ruby-head
  - jruby-head

before_install:
  - gem install bundler -v 1.10.6
  - gem update --system
  - gem --version

gemfile:
  - Gemfile

notifications:
  email: false
